name: Build Signed APK
on: 
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}
        run: |
          echo "$ENCODED_KEYSTORE" | base64 -di > app/keystore.jks
      
      # 修复后的签名步骤
      - name: Build Signed APK
        run: |
          ./gradlew assembleRelease \
            -PstoreFile='app/keystore.jks' \
            -PstorePassword=${{ secrets.KEYSTORE_PASSWORD }} \
            -PkeyAlias=${{ secrets.KEY_ALIAS }} \
            -PkeyPassword=${{ secrets.KEY_PASSWORD }}
          
          # 验证文件已签名
          ls -l app/build/outputs/apk/release/*.apk
      
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-app-release
          path: app/build/outputs/apk/release/*.apk
          retention-days: 1
