name: Build APK
on: 
  push:
    branches: [ main ]  # 推送到 main 分支时触发
    tags: [ 'v*' ]      # 或推送版本标签（如 v1.0）时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 JDK 环境
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # 3. 授予 Gradle 执行权限
      - name: Grant Gradle permission
        run: chmod +x ./gradlew

      # 4. 构建 Release APK
      - name: Build APK
        run: ./gradlew assembleRelease

      # 5. 上传 APK 到 Artifacts（供手动下载）
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

      # 6. 发布到 GitHub Releases（可选）
      - name: Release APK
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')  # 仅标签触发时发布
        with:
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动使用内置 token
