name: Build Signed APK
on: 
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 JDK 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 授予 Gradle 执行权限
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 4. ⭐ 密钥还原步骤（核心操作）
      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}  # Base64 编码的密钥内容
        run: |
          echo "$ENCODED_KEYSTORE" | base64 -di > app/keystore.jks  # 解码并输出到文件
          ls -la app/keystore.jks  # 验证文件生成（调试用）

      # 5. 构建签名 APK
      - name: Build Release APK
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      # 6. 上传 APK 产物
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-app-release
          path: app/build/outputs/apk/release/*.apk
          retention-days: 1  # 添加缓存清理时间
