name: Build Signed APK
on: 
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}
        run: echo "$ENCODED_KEYSTORE" | base64 -d > app/keystore.p12

      - name: Verify Keystore File
        run: |
          ls -l app/keystore.p12
          file app/keystore.p12
      
      - name: Build Signed APK
        run: ./gradlew assembleRelease
      
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-app-release
          path: app/build/outputs/apk/release/*.apk
          retention-days: 1
