name: Android Build and Release

on:
  push:
    branches: [ '**' ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign
        with:
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: mv "${{ steps.sign.outputs.signedReleaseFile }}" app-release_${{ github.run_id }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0-${{ github.run_id }}
          name: Release v1.0 (Build ${{ github.run_id }})
          files: app-release_*.apk
          token: ${{ secrets.GITHUB_TOKEN }}
